export const COMMON_GRAVITATIONAL_CONSTANT = 0.3;
export const BLACK_HOLE_GRAVITY_COEFFICIENT = 10;
export const STAR_GRAVITY_COEFFICIENT = 1;

export const PARTICLE_RADIUS = 1;

export const STAR_DISAPPEAR_RADIUS = 5;
export const STAR_RADIUS_SUB_ON_UPDATE = 0.0008;
export const STAR_MIN_RADIUS = 10;
export const STAR_MAX_RADIUS = 60;
export const STAR_MAX_MINUS_MIN = STAR_MAX_RADIUS - STAR_MIN_RADIUS;
export const STAR_HOVER_RADIUS_INC = 0.08;

export const SUPERNOVA_RADIUS_INC = 0.8;
export const SUPERNOVA_RADIUS_DEC = 2.8;
export const SUPERNOVA_RADIUS_MIN = STAR_MIN_RADIUS * 1.4;
export const SUPERNOVA_RADIUS_MAX = STAR_MAX_RADIUS * 1.4;
export const SUPERNOVA_STAR_SPAWN_RADIUS = STAR_MIN_RADIUS * 1.4;
export const SUPERNOVA_MIN_STARS_SPAWN = 0.7; // range for random
export const SUPERNOVA_MAX_STARS_SPAWN = 2.9; // range for random
export const SUPERNOVA_STAR_SPAWN_MIN_VELOCITY = 0.2;
export const SUPERNOVA_STAR_SPAWN_MAX_VELOCITY = 0.4;
export const SUPERNOVA_MIN_PARTICLE_SPAWN = 50;
export const SUPERNOVA_MAX_PARTICLE_SPAWN = 120;
export const SUPERNOVA_PARTICLE_SPAWN_MIN_VELOCITY = 0.2;
export const SUPERNOVA_PARTICLE_SPAWN_MAX_VELOCITY = 0.4;

export const CANVAS2D_BLACK_HOLE_POOL_CAPACITY = 1000;
export const CANVAS2D_STAR_POOL_CAPACITY = 5000;
export const CANVAS2D_PARTICLE_POOL_CAPACITY = 250000;

export const WEBGL_BLACK_HOLE_POOL_CAPACITY = 1000;
export const WEBGL_STAR_POOL_CAPACITY = 5000;
export const WEBGL_PARTICLE_POOL_CAPACITY = 500000;

export const INITIAL_STAR_COUNT = 2;
export const INITIAL_BLACK_HOLE_COUNT = 1;
export const INITIAL_BLACK_HOLE_RADIUS = 10;

export const STAR_COLLISION_COEFFICIENT = 0.8;
export const STAR_ABSORB_MULTIPLIER = 2;

/**
 * Coefficient of particles which must be multiplied with star mass to get the number of particles after explosion
 */
export const PARTICLES_AFTER_STAR_EXP_MIN_COUNT = 15;
export const PARTICLES_AFTER_STAR_EXP_MAX_COUNT = 40;
export const PARTICLES_AFTER_STAR_EXP_MIN_R = 0.6;
export const PARTICLES_AFTER_STAR_EXP_MAX_R = 0.95;

export const PARTICLES_AFTER_STAR_EXP_MIN_V = 0.2;
export const PARTICLES_AFTER_STAR_EXP_MAX_V = 0.22;

/**
 * 5 seconds
 */
export const FIRST_BLACK_HOLE_TIME_REMAINS = 5000;
/**
 * 60 seconds
 */
export const NEXT_BLACK_HOLE_TIME_REMAINS = 60000;
/**
 * Show black hole time when remain 10 seconds
 */
export const BLACK_HOLE_TIME_APPEAR_MIN_TIME = 10000;

export const BLACK_HOLE_STAR_ABSORB_SIZE_MULTIPLIER = 10;
export const BLACK_HOLE_STAR_ABSORB_DISTANCE_MIN = 250;
export const BLACK_HOLE_STAR_ABSORB_PARTICLES_GENERATE_MULTIPLIER = 3;
export const BLACK_HOLE_STAR_ABSORB_RADIUS_MULTIPLIER = 0.012;
export const BLACK_HOLE_STAR_ABSORB_PARTICLES_MIN_R = 0.99;
export const BLACK_HOLE_STAR_ABSORB_PARTICLES_MAX_R = 1.05;
